server:
  port: 8085

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**
        - id: theater-service
          uri: lb://THEATER-SERVICE
          predicates:
            - Path=/api/v1/theaters/**
        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/api/v1/movies/**
        - id: show-service
          uri: lb://SHOW-SERVICE
          predicates:
            - Path=/api/v1/shows/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: false