server:
  port: ${PORT:8080}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 60000
        response-timeout: 60000
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE, INTERNAL_SERVER_ERROR, TOO_MANY_REQUESTS
            methods: GET, POST, PUT, DELETE
            backoff:
              firstBackoff: 1000ms
              maxBackoff: 10000ms
              factor: 2
              basedOnPreviousValue: false
        - SetRequestHeader=User-Agent, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
      routes:
        - id: movie-service
          uri: ${MOVIE_SERVICE_URL}
          predicates:
            - Path=/api/v1/movies/**
          filters:
            - TokenRelay
        - id: theater-service
          uri: ${THEATER_SERVICE_URL}
          predicates:
            - Path=/api/v1/theaters/**
          filters:
            - TokenRelay
        - id: show-service
          uri: ${SHOW_SERVICE_URL}
          predicates:
            - Path=/api/v1/shows/**
          filters:
            - TokenRelay
        - id: booking-service
          uri: ${BOOKING_SERVICE_URL}
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - TokenRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
