server:
  port: ${PORT:8080}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 60000
        response-timeout: 60000
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE, INTERNAL_SERVER_ERROR, TOO_MANY_REQUESTS
            methods: GET, PUT
            backoff:
              firstBackoff: 1000ms
              maxBackoff: 10000ms
              factor: 2
              basedOnPreviousValue: false

      routes:
        - id: movie-service
          uri: ${MOVIE_SERVICE_URL}
          predicates:
            - Path=/api/v1/movies/**
          filters:
            - TokenRelay
        - id: theater-service
          uri: ${THEATER_SERVICE_URL}
          predicates:
            - Path=/api/v1/theaters/**
          filters:
            - TokenRelay
        - id: show-service
          uri: ${SHOW_SERVICE_URL}
          predicates:
            - Path=/api/v1/shows/**
          filters:
            - TokenRelay
        - id: booking-service
          uri: ${BOOKING_SERVICE_URL}
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - TokenRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}


logging:
  level:
    org.springframework.cloud.gateway: WARN
    org.springframework.http.server.reactive: WARN
    org.springframework.web.reactive: WARN
    reactor.netty: WARN
