server:
  port: 8085

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/bookings/**
        - id: theater-service
          uri: lb://THEATER-SERVICE
          predicates:
            - Path=/theaters/**
        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movies/**
        - id: show-service
          uri: lb://SHOW-SERVICE
          predicates:
            - Path=/shows/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka